default_job = "run"

[jobs.run]
command = ["cargo", "run", "--color", "always"]
watch = [ "public", "templates" ]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.css]
command = ["tailwindcss", "-m", "-i", "input.css", "-o", "public/styles/tailwind.css"]
watch = [ "input.css", "tailwind.config.js", "templates", "public" ]
need_stdout = false
allow_warnings = true
background = false

