services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8000:8000
  postgres:
    image: postgres:16-alpine
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrate:
    image: arigaio/atlas:latest-alpine
    command: >
      migrate apply --url postgres://admin:password@postgres:5432/portfolio?sslmode=disable&search_path=public
    networks:
      - db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/:/migrations
networks:
  db:
volumes:
  postgres_data:
