app = 'ryan-brink-portfolio'
primary_region = 'iad'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[build]
image = "portfolio"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
